const catalogo = [

/*=========================================
            BARBIE
=========================================*/

{
    id:1,
    nome:"Barbie e os Rockers: Fora Deste Mundo",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:1987,
    nota:8.0,
    duracao:"25 min",
    genero:["Musical","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20os%20Rockers%20Fora%20Deste%20Mundo.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/Barbie%20e%20os%20Rockers%20Fora%20Deste%20Mundo.png",
    video:"",
    sinopse:"Barbie e sua banda, os Rockers, embarcam em uma aventura espacial para realizar um show inesquecível.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:2,
    nome:"Barbie em O Quebra-Nozes",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2001,
    nota:8.0,
    duracao:"1h16",
    genero:["Princesas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Em%20Quebra%20Nozes.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20em%20O%20Quebra%20Nozes.png",
    video:"https://screenapp.io/app/api/public/files/Y78OIWlD_MGI8MvtGxeaKfgx",
    sinopse:"Clara embarca em uma aventura mágica ao lado do Quebra-Nozes para derrotar o Rei dos Ratos.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:3,
    nome:"Barbie como Rapunzel",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2002,
    nota:8.0,
    duracao:"1h24",
    genero:["Princesas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20como%20Rapunzel.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20como%20Rapunzel%205r45.png",
    video:"https://screenapp.io/app/api/public/files/6687QD3Gdl6gwMBflkJLiyMG",
    sinopse:"Rapunzel usa sua coragem e criatividade para mudar seu destino.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:4,
    nome:"Barbie e o Lago dos Cisnes",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2003,
    nota:8.0,
    duracao:"1h23",
    genero:["Princesas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Lago%20dos%20Cisnes.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20em%20Lago%20dos%20Cisnes.png",
    video:"https://screenapp.io/app/api/public/files/tvFw_jxBKR2kd-896wTn_Ozh",
    sinopse:"Odette enfrenta um poderoso feiticeiro para salvar a Floresta Encantada.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:5,
    nome:"Barbie: A Princesa e a Plebeia",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2004,
    nota:8.0,
    duracao:"1h25",
    genero:["Princesas","Musical"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20em%20a%20Princesa%20e%20a%20Plebeia.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20A%20Princesa%20e%20a%20Plebeia.png",
    video:"",
    sinopse:"Uma princesa e uma garota comum descobrem que são idênticas e trocam de lugar.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:6,
    nome:"Barbie Fairytopia",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2005,
    nota:8.0,
    duracao:"1h10",
    genero:["Fadas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/barbie%20fairytopia.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Fairytopia.png",
    video:"",
    sinopse:"Elina parte em uma jornada para salvar Fairytopia.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:7,
    nome:"Barbie e a Magia de Pegasus",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2005,
    nota:8.0,
    duracao:"1h25",
    genero:["Princesas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20em%20a%20Magia%20de%20Aladus.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20e%20a%20Magia%20de%20Pegasus.png",
    video:"",
    sinopse:"Annika luta contra um terrível feiticeiro com a ajuda de um cavalo alado.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:8,
    nome:"Barbie Fairytopia Mermaidia",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2006,
    nota:8.0,
    duracao:"1h15",
    genero:["Sereias","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Fairytopia%20Mermaidia.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Fairytopia%20Mermaidia.png",
    video:"",
    sinopse:"Elina viaja para Mermaidia para salvar um príncipe.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:9,
    nome:"O Diário da Barbie",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2006,
    nota:8.0,
    duracao:"1h10",
    genero:["Infantil","Drama"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/O%20Diario%20da%20Barbie%205234.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20O%20Diario%20da%20Barbie.png",
    video:"",
    sinopse:"Barbie vive os desafios da escola enquanto escreve em seu diário.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:10,
    nome:"Barbie em as 12 Princesas Bailarinas",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2006,
    nota:8.0,
    duracao:"1h22",
    genero:["Princesas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20As%2012%20Princesas%20Bailarinas.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20em%20As%2012%20Princesas%20Bailarinas.png",
    video:"",
    sinopse:"Doze irmãs descobrem um reino mágico escondido.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:11,
    nome:"Barbie Fairytopia: A Magia do Arco-Íris",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2007,
    nota:8.0,
    duracao:"1h15",
    genero:["Fadas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Fairytopia%20A%20Magia%20do%20Arco%20iris.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Fairytopia%20A%20Magia%20do%20Arco%20iris.png",
    video:"",
    sinopse:"Elina precisa unir as fadas para salvar o primeiro arco-íris da primavera.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:12,
    nome:"Barbie: A Princesa da Ilha",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2007,
    nota:8.0,
    duracao:"1h26",
    genero:["Princesas","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20em%20A%20Princesa%20da%20Ilha.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20A%20Princesa%20da%20Ilha.png",
    video:"https://screenapp.io/app/api/public/files/NNZJth4wRLTxuLBSFuM_SZgO",
    sinopse:"Ro vive em uma ilha paradisíaca até descobrir seu verdadeiro destino como princesa.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:13,
    nome:"Barbie Butterfly A Nova Aventura Em Fairytopia",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2008,
    nota:8.0,
    duracao:"1h15",
    genero:["Fadas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Butterfly%20A%20Nova%20Aventura%20Em%20Fairytopia.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Mariposa%20and%20her%20Butterfly%20Fairy%20Friends.png",
    video:"",
    sinopse:"Mariposa embarca em uma missão para salvar a Rainha das Fadas Borboletas.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:14,
    nome:"Barbie e o Castelo de Diamante",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2008,
    nota:8.0,
    duracao:"1h18",
    genero:["Musical","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/barbie%20castelo%20de%20diamante.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20e%20o%20Castelo%20de%20Diamante.png",
    video:"https://screenapp.io/app/api/public/files/3YRNKvoxFDB2jD7EKpluFxQK",
    sinopse:"Duas amigas enfrentam uma feiticeira para proteger um castelo mágico.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:15,
    nome:"Barbie Em A Canção De Natal",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2008,
    nota:8.0,
    duracao:"1h16",
    genero:["Natal","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Em%20A%20Cancao%20De%20Natal.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Em%20A%20Cancao%20De%20Natal.png",
    video:"",
    sinopse:"Barbie interpreta uma adaptação encantadora do clássico Conto de Natal.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:16,
    nome:"Barbie Em A Pequena Polegar",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2009,
    nota:8.0,
    duracao:"1h15",
    genero:["Fadas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/4a7d8114438a0ca78cdcc526d790a8ef695669413e4419dc238462c81d3097fb.jpg",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Em%20A%20Pequena%20Polegar.png",
    video:"",
    sinopse:"Polegarzinha descobre que até os menores podem fazer grandes diferenças.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:17,
    nome:"Barbie e as Três Mosqueteiras",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2009,
    nota:8.0,
    duracao:"1h21",
    genero:["Aventura","Princesas"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20as%20Tres%20Mosqueteiras.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20e%20as%20Tres%20Mosqueteiras.png",
    video:"",
    sinopse:"Corinne sonha em se tornar mosqueteira e proteger o príncipe.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:18,
    nome:"Barbie em Vida de Sereia",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2010,
    nota:8.0,
    duracao:"1h15",
    genero:["Sereias","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20em%20Vida%20de%20Sereia.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/Barbie%20em%20Vida%20de%20Sereia.png",
    video:"https://screenapp.io/app/api/public/files/Po-dxsUe_6HOpl4omAe826wU",
    sinopse:"Merliah descobre que é metade sereia e precisa salvar o reino submarino.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:19,
    nome:"Barbie: Moda e Magia",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2010,
    nota:8.0,
    duracao:"1h19",
    genero:["Fantasia","Moda"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Moda%20e%20Magia.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Moda%20e%20Magia.png",
    video:"https://screenapp.io/app/api/public/files/vGNsb3JYNBepXgnzKKNRmHKu",
    sinopse:"Barbie vai para Paris e ajuda a salvar uma famosa casa de moda.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:20,
    nome:"Barbie: O Segredo das Fadas",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2011,
    nota:8.0,
    duracao:"1h12",
    genero:["Fadas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20E%20o%20Segredo%20Das%20Fadas.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20O%20Segredo%20das%20Fadas.png",
    video:"",
    sinopse:"Barbie descobre um mundo secreto de fadas enquanto tenta salvar Ken.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:21,
    nome:"Barbie: Escola de Princesas",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2011,
    nota:8.0,
    duracao:"1h20",
    genero:["Princesas","Infantil"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Escola%20de%20Princesas.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Escola%20de%20Princesas.png",
    video:"https://screenapp.io/app/api/public/files/lI3trM26cll2nGWiTXrcwPoj",
    sinopse:"Blair é convidada para estudar em uma escola onde aprende a ser princesa.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:22,
    nome:"Barbie: Um Natal Perfeito",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2011,
    nota:8.0,
    duracao:"1h14",
    genero:["Natal","Infantil"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Um%20Natal%20Perfeito.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Um%20Natal%20Perfeito.png",
    video:"",
    sinopse:"Barbie e suas irmãs vivem uma aventura natalina cheia de música e amizade.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:23,
    nome:"Barbie em Vida de Sereia 2",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2012,
    nota:8.0,
    duracao:"1h14",
    genero:["Sereias","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Em%20Vida%20de%20Sereia%202.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20em%20Vida%20de%20Sereia%202.png",
    video:"",
    sinopse:"Merliah retorna ao reino submarino para enfrentar uma nova ameaça.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:24,
    nome:"Barbie: A Princesa e a Pop Star",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2012,
    nota:8.0,
    duracao:"1h26",
    genero:["Musical","Infantil"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20em%20a%20Princesa%20e%20a%20Pop%20Star.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20A%20Princesa%20e%20a%20Pop%20Star.png",
    video:"",
    sinopse:"Uma princesa e uma estrela da música trocam de lugar para descobrir quem realmente são.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:25,
    nome:"Barbie e as Sapatilhas Mágicas",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2013,
    nota:8.0,
    duracao:"1h15",
    genero:["Princesas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20as%20Sapatilhas%20Magicas.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20e%20As%20Sapatilhas%20Magicas.png",
    video:"https://screenapp.io/app/api/public/files/XfrE2Ry7Yqu0R-3d6ybLkQgr",
    sinopse:"Kristyn encontra um par de sapatilhas mágicas que a levam para mundos encantados.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:26,
    nome:"Barbie Mariposa e a Princesa das Fadas",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2013,
    nota:8.0,
    duracao:"1h15",
    genero:["Fadas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Butterfly%20A%20Nova%20Aventura%20Em%20Fairytopia.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Mariposa%20and%20her%20Butterfly%20Fairy%20Friends.png",
    video:"",
    sinopse:"Mariposa faz amizade com uma princesa fada para salvar dois reinos.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:27,
    nome:"Barbie e Suas Irmãs em Uma Aventura de Cavalos",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2013,
    nota:8.0,
    duracao:"1h12",
    genero:["Aventura","Infantil"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20Suas%20Irmas%20em%20uma%20Aventura%20de%20Cavalos.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20e%20Suas%20Irmas%20em%20Uma%20Aventura%20de%20Cavalos.png",
    video:"",
    sinopse:"Barbie e suas irmãs vivem aventuras inesquecíveis em uma academia de cavalos.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:28,
    nome:"Barbie: A Princesa das Pérolas",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2014,
    nota:8.0,
    duracao:"1h13",
    genero:["Sereias","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20%20A%20sereia%20das%20Perolas.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20A%20Princesa%20das%20Perolas.png",
    video:"",
    sinopse:"Lumina descobre que possui poderes mágicos ligados às pérolas.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:29,
    nome:"Barbie e a Porta Secreta",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2014,
    nota:8.0,
    duracao:"1h21",
    genero:["Princesas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20o%20Portal%20Secreto.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20e%20o%20Portal%20Secreto.png",
    video:"",
    sinopse:"Uma princesa encontra uma porta que leva a um reino mágico cheio de criaturas encantadas.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:30,
    nome:"Barbie Super Princesa",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2015,
    nota:8.0,
    duracao:"1h14",
    genero:["Heroínas","Ação"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20%20Super%20Princesa.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Super%20Princesa.png",
    video:"",
    sinopse:"Depois de ganhar superpoderes, Kara precisa proteger seu reino.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:31,
    nome:"Barbie: Rock'n Royals",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2015,
    nota:8.0,
    duracao:"1h24",
    genero:["Musical","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Rainhas%20do%20Rock.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Rockn%20Royals.png",
    video:"",
    sinopse:"Uma princesa e uma estrela do rock trocam de acampamento e descobrem novos talentos.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:32,
    nome:"Barbie e Suas Irmãs em Uma Aventura de Cachorrinhos",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2015,
    nota:8.0,
    duracao:"1h16",
    genero:["Aventura","Infantil"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20Suas%20Irmas%20em%20Uma%20Aventura%20de%20Cachorrinhos.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20e%20Suas%20Irmas%20em%20Uma%20Aventura%20de%20Cachorrinhos.png",
    video:"",
    sinopse:"Barbie e suas irmãs encontram um mapa do tesouro escondido e vivem uma grande aventura ao lado dos filhotes.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:33,
    nome:"Barbie: E as Agentes Secretas",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2016,
    nota:8.0,
    duracao:"1h15",
    genero:["Espiãs","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20as%20Agentes%20Secretas.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20E%20as%20Agentes%20Secretas.png",
    video:"",
    sinopse:"Barbie e suas amigas se tornam agentes secretas para impedir um misterioso ladrão.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:34,
    nome:"Barbie: Aventura nas Estrelas",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2016,
    nota:8.0,
    duracao:"1h19",
    genero:["Ficção","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Aventura%20Nas%20Estrelas.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Aventura%20nas%20Estrelas.png",
    video:"",
    sinopse:"Barbie viaja pelo espaço para salvar as estrelas da galáxia.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:35,
    nome:"Barbie: Heroína dos Videogames",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2017,
    nota:8.0,
    duracao:"1h12",
    genero:["Videogame","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20em%20Um%20Mundo%20de%20Video%20Game.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Video%20Game%20Hero.png",
    video:"",
    sinopse:"Barbie entra em um videogame e precisa vencer desafios para salvar o mundo digital.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:36,
    nome:"Barbie: Golfinhos Mágicos",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2017,
    nota:8.0,
    duracao:"1h03",
    genero:["Sereias","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20os%20Golfinhos%20Magicos.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Golfinhos%20Magicos.png",
    video:"",
    sinopse:"Durante férias em uma ilha, Barbie conhece golfinhos mágicos e vive uma nova aventura.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:37,
    nome:"Barbie: Aventura de Princesa",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2020,
    nota:8.0,
    duracao:"1h12",
    genero:["Princesas","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Princess%20Adventure.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Aventura%20de%20Princesa.png",
    video:"",
    sinopse:"Barbie conhece uma princesa muito parecida com ela e embarca em uma aventura real.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:38,
    nome:"Barbie: Grande Cidade, Grandes Sonhos",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2021,
    nota:8.0,
    duracao:"1h02",
    genero:["Musical","Infantil"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Grandes%20Sonhos%20na%20Cidade.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Grande%20Cidade%20Grandes%20Sonhos.png",
    video:"",
    sinopse:"As duas Barbies vivem uma emocionante jornada musical em Nova York.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:39,
    nome:"Barbie: O Poder das Sereias",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2022,
    nota:8.0,
    duracao:"1h05",
    genero:["Sereias","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Poder%20da%20Sereia.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20O%20Poder%20das%20Sereias.png",
    video:"",
    sinopse:"Malibu e Brooklyn embarcam em uma aventura submarina para descobrir seus poderes.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:40,
    nome:"Barbie: Skipper e a Grande Aventura de Babá",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2023,
    nota:8.0,
    duracao:"1h00",
    genero:["Aventura","Infantil"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Skipper%20e%20a%20Grande%20Aventura%20de%20Babas.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Skipper%20e%20a%20Grande%20Aventura%20de%20Baba.png",
    video:"",
    sinopse:"Skipper assume um novo desafio enquanto cuida de várias crianças em uma aventura divertida.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:41,
    nome:"Barbie: Uma Viagem Épica",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2022,
    nota:8.0,
    duracao:"36 min",
    genero:["Interativo","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Uma%20Viagem%20epica%20de%20Carro.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Uma%20Viagem%20epica.png",
    video:"",
    sinopse:"Um filme interativo em que você escolhe os caminhos da aventura da Barbie.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:42,
    nome:"Barbie",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2023,
    nota:6.9,
    duracao:"1h 54min",
    genero:["Comédia","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie.png",
    video:"",
    trailer:"https://youtube.com/...",
    sinopse:"Depois de uma crise existencial, Barbie parte para o mundo real.",
    elenco:[
        "Margot Robbie",
        "Ryan Gosling"
    ],
    diretor:"Greta Gerwig",
    novo:true,
    recomendado:true
},

{
    id:43,
    nome:"Barbie & Chelsea: O Aniversário Perdido",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2021,
    nota:8.0,
    duracao:"1h00",
    genero:["Aventura","Infantil"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20Chelsea%20%20O%20Aniversario%20Perdido.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20e%20Chelsea%20O%20Aniversario%20Perdido.png",
    video:"",
    sinopse:"Chelsea acredita que perdeu seu aniversário durante uma viagem de navio e parte em uma divertida aventura para tentar recuperá-lo.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:44,
    nome:"Barbie e Suas Irmãs em Busca dos Cachorrinhos",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2016,
    nota:8.0,
    duracao:"1h16",
    genero:["Aventura","Infantil"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20Suas%20Irmas%20em%20Busca%20dos%20Cachorrinhos.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20e%20Suas%20Irmas%20em%20Busca%20dos%20Cachorrinhos.png",
    video:"",
    sinopse:"Durante um festival tropical, Barbie e suas irmãs precisam encontrar seus filhotes desaparecidos antes do grande desfile.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:45,
    nome:"Barbie: Vida na Casa dos Sonhos",
    tipo:"Série",
    categoria:"Séries",
    colecao:"Barbie",
    ano:2012,
    nota:8.0,
    duracao:"7 Temporadas",
    genero:["Infantil","Comédia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20A%20Vida%20na%20Casa%20dos%20Sonhos.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Vida%20na%20Casa%20dos%20Sonhos.png",
    video:"",
    sinopse:"Acompanhe Barbie, Ken, suas irmãs e amigos vivendo aventuras engraçadas na famosa Casa dos Sonhos em Malibu.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:46,
    nome:"Barbie Dreamhouse Adventures",
    tipo:"Série",
    categoria:"Séries",
    colecao:"Barbie",
    ano:2018,
    nota:8.0,
    duracao:"5 Temporadas",
    genero:["Infantil","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Aventuras%20na%20Casa%20dos%20Sonhos%20da%20Barbie.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Dreamhouse%20Adventures.png",
    video:"",
    sinopse:"Barbie, suas irmãs e seus amigos vivem novas aventuras, desafios e momentos divertidos na Dreamhouse.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:47,
    nome:"Barbie: São Necessárias Duas",
    tipo:"Série",
    categoria:"Séries",
    colecao:"Barbie",
    ano:2022,
    nota:8.0,
    duracao:"2 Temporadas",
    genero:["Infantil","Musical"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20preciso%20dois.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Sao%20Necessarias%20Duas.png",
    video:"",
    sinopse:"Malibu e Brooklyn seguem seus sonhos na música enquanto vivem novas aventuras e fortalecem sua amizade.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:48,
    nome:"Barbie: Um Toque de Magia",
    tipo:"Série",
    categoria:"Séries",
    colecao:"Barbie",
    ano:2023,
    nota:8.0,
    duracao:"2 Temporadas",
    genero:["Infantil","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Um%20Toque%20de%20Magica.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Um%20Toque%20de%20Magia.png",
    video:"",
    sinopse:"Duas Barbies encontram uma jovem com poderes mágicos e embarcam em aventuras repletas de fantasia.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:50,
    nome:"Barbie Mistérios: A Grande Perseguição a Cavalo",
    tipo:"Série",
    categoria:"Séries",
    colecao:"Barbie",
    ano:2024,
    nota:8.0,
    duracao:"Série",
    genero:["Mistério","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Misterios%20da%20Barbie.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Misterios%20A%20Grande%20Perseguicao%20a%20Cavalo.png",
    video:"",
    sinopse:"Malibu e Brooklyn investigam um misterioso desaparecimento durante uma competição de cavalos.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:51,
    nome:"Barbie e Teresa: Receita para a Amizade",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2025,
    nota:8.8,
    duracao:"1h 02min",
    genero:["Infantil"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Assista%20Barbie%20e%20Teresa%20Receita%20para%20a%20Amizade.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20e%20Teresa%20Receita%20para%20a%20Amizade.png",
    dublado:true,
    legendado:true,
    novo:true
},
/*=========================================
            BARBIE
=========================================*/





/*=========================================
            MONSTER HIGH
=========================================*/
{
    id:101,
    nome:"Monster High: O Novo Fantasma da Escola",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"MonsterHigh",
    ano:2010,
    nota:8.0,
    duracao:"23min",
    genero:["Infantil","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20O%20Novo%20Fantasma%20da%20Escola.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20O%20Novo%20Fantasma%20da%20Escola.png",
    video:"",
    novo:false
},

{
    id:102,
    nome:"Monster High: Choque de Cultura: Presas x Pelos",
    ano:2011,
    nota:8.1,
    duracao:"46min",
    genero:["Infantil","Fantasia"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Choque%20de%20Cultura%20Presas%20x%20Pelos.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Choque%20de%20Cultura%20Presas%20x%20Pelos.png",
    video:"LINK_VIDEO"
},

{
    id:103,
    nome:"Monster High: Por que os Monstros se Apaixonam?",
    ano:2012,
    nota:8.2,
    duracao:"44min",
    genero:["Romance","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Por%20que%20os%20Monstros%20se%20Apaixonam.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Por%20que%20os%20Monstros%20se%20Apaixonam.png",
    video:"LINK_VIDEO"
},

{
    id:104,
    nome:"Monster High: Fuga da Ilha do Esqueleto",
    ano:2012,
    nota:8.0,
    duracao:"45min",
    genero:["Aventura","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Fuga%20da%20Ilha%20do%20Esqueleto.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Fuga%20da%20Ilha%20do%20Esqueleto.png",
    video:"LINK_VIDEO"
},

{
    id:105,
    nome:"Monster High: Uma Festa de Arrepiar",
    ano:2012,
    nota:8.0,
    duracao:"46min",
    genero:["Fantasia","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Uma%20Festa%20de%20Arrepiar.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Uma%20Festa%20de%20Arrepiar.png",
    video:"LINK_VIDEO"
},

{
    id:106,
    nome:"Monster High: Os Pesadelos de Monster High",
    ano:2012,
    nota:8.0,
    duracao:"46min",
    genero:["Esporte","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Os%20Pesadelos%20de%20Monster%20High.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Os%20Pesadelos%20de%20Monster%20High.png",
    video:"LINK_VIDEO"
},

{
    id:107,
    nome:"Monster High: Scaris, a Cidade Sem Luz",
    ano:2013,
    nota:8.2,
    duracao:"61min",
    genero:["Aventura","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Scaris%20City%20of%20Frights.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Scaris%20City%20of%20Frights.png",
    video:"LINK_VIDEO"
},

{
    id:108,
    nome:"Monster High: 13 Monster Desejos",
    ano:2013,
    nota:8.5,
    duracao:"73min",
    genero:["Fantasia","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%2013%20Monster%20Desejos.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%2013%20Monster%20Desejos.png",
    video:"LINK_VIDEO"
},

{
    id:109,
    nome:"Monster High: Monstros, Câmera, Ação!",
    ano:2014,
    nota:8.4,
    duracao:"74min",
    genero:["Aventura","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Monstros%20Camera%20Acao.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Monstros%20Camera%20Acao.jpg",
    video:"LINK_VIDEO"
},

{
    id:110,
    nome:"Monster High: Uma Fusão Muito Louca",
    ano:2014,
    nota:8.1,
    duracao:"73min",
    genero:["Fantasia","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Uma%20Fusao%20Muito%20Louca.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Uma%20Fusao%20Muito%20Louca.png",
    video:"LINK_VIDEO"
},

{
    id:111,
    nome:"Monster High: Assombrada",
    ano:2015,
    nota:8.5,
    duracao:"75min",
    genero:["Fantasia","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Haunted.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Haunted.png",
    video:"LINK_VIDEO"
},

{
    id:112,
    nome:"Monster High: Boo York, Boo York",
    ano:2015,
    nota:8.3,
    duracao:"72min",
    genero:["Musical","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Boo%20York%20Boo%20York.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Boo%20York%20Boo%20York.png",
    video:"LINK_VIDEO"
},

{
    id:113,
    nome:"Monster High: A Assustadora Barreira de Coral",
    ano:2016,
    nota:8.0,
    duracao:"70min",
    genero:["Aventura","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Great%20Scarrier%20Reef.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Great%20Scarrier%20Reef.png",
    video:"LINK_VIDEO"
},

{
    id:114,
    nome:"Bem-Vindos a Monster High",
    ano:2016,
    nota:7.8,
    duracao:"73min",
    genero:["Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20Bem%20Vindos%20a%20Monster%20High.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20Bem%20Vindos%20a%20Monster%20High.png",
    video:"LINK_VIDEO"
},

{
    id:115,
    nome:"Monster High: Eletrizante",
    ano:2017,
    nota:7.7,
    duracao:"71min",
    genero:["Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Eletrizante.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Eletrizante.png",
    video:"LINK_VIDEO"
},

{
    id:116,
    nome:"Monster High: O Filme",
    ano:2022,
    nota:7.9,
    duracao:"1h 32min",
    genero:["Musical","Fantasia"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20O%20Filme.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20O%20Filme.png",
    video:"LINK_VIDEO"
},

{
    id:117,
    nome:"Monster High 2",
    ano:2023,
    nota:8.0,
    duracao:"1h 33min",
    genero:["Musical","Fantasia"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%202.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%202.png",
    video:"LINK_VIDEO"
},
/*=========================================
            MONSTER HIGH
=========================================*/





/*=========================================
            NOVELAS
=========================================*/

{
    id:201,
    nome:"Avenida Brasil",
    ano:2012,
    nota:9.4,
    duracao:"179 capítulos",
    genero:["Drama"],
    categoria:"Novelas",
    colecao:"Avenida Brasil",
    tipo:"Novela",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/Videos/Novela%20Avenida%20Brasil.png",
    banner:"https://image.tmdb.org/t/p/original/xxxxxxxx.jpg",
    pagina:"pages/avenida-brasil.html",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:202,
    nome:"Pantanal",
    ano:2022,
    nota:9.1,
    duracao:"167 capítulos",
    genero:["Drama"],
    categoria:"Novelas",
    colecao:"Pantanal",
    tipo:"Novela",
    poster:"https://image.tmdb.org/t/p/w500/yyyyyyyy.jpg",
    banner:"https://image.tmdb.org/t/p/original/yyyyyyyy.jpg",
    pagina:"pages/pantanal.html",
    dublado:true,
    legendado:false,
    novo:false
},
{
    id:203,
    nome:"Coração Acelerado",
    ano:2025,
    nota:9.0,
    duracao:"161 capítulos",
    genero:["Drama"],
    categoria:"Novelas",
    colecao:"Globo",
    tipo:"Novela",
    poster:"https://onacaokuwgiflhliitlt.supabase.co/storage/v1/object/public/filme/Coracao%20Acelerado.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/Videos/banner%20coracao%20acelerado.png",
    sinopse:"A nova novela das sete da Globo.",
    totalEpisodios:161,
    baseVideo:"https://23rzv4udpdbv8t6.cdn-novflix.com/storage1/CORACE/CORACE-",
    novo:true
},

{
    id:204,
    nome:"Maria do Bairro",
    ano:1995,
    nota:8.1,
    duracao:"185 capítulos",
    genero:["Drama","Romance"],
    categoria:"Novelas",
    colecao:"Maria do Bairro",
    tipo:"Novela",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Maria%20do%20Bairro.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Maria%20do%20Bairro.png",
    sinopse:"Maria do Bairro é uma jovem humilde que, após ser acolhida por uma família rica, enfrenta diferenças sociais, conflitos familiares e uma história de amor cheia de reviravoltas.",
    totalEpisodios:185,

    baseVideo:"https://23rzv4udpdbv8t6.cdn-novflix.com/storage3/MDB/MDBzJ8ZbkUekz24eeeVxdBUi",

    dublado:true,
    legendado:false,
    novo:false
},
/*=========================================
            NOVELAS
=========================================*/

{
    id: 10,
    nome: "Obsessão",
    ano: 2025,
    nota: 7.8,
    duracao: "1h 40min",
    genero: ["Suspense","Drama"],
    categoria: "Filmes",
    colecao: "Obsessão",
    tipo: "Filme",
    poster: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/Videos/filme%20obsessao.png",
    banner: "https://onacaokuwgiflhliitlt.supabase.co/storage/v1/object/public/filme/banner%20Obsessao.png",
    video:"https://link-do-video",
    pagina: "pages/obsessao.html",
    dublado: true,
    legendado: true,
    novo: true
},

];