const catalogo = [

/*=========================================
            BARBIE
=========================================*/
{
    id:1,
    nome:"Barbie e os Rockers: Fora Deste Mundo",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:1987,
    nota:8.0,
    duracao:"25 min",
    genero:["Musical","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20os%20Rockers%20Fora%20Deste%20Mundo.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/Barbie%20e%20os%20Rockers%20Fora%20Deste%20Mundo.png",
    video:"",
    sinopse:"Barbie e sua banda, os Rockers, embarcam em uma aventura espacial para realizar um show inesquecível.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:2,
    nome:"Barbie em O Quebra-Nozes",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2001,
    nota:8.0,
    duracao:"1h16",
    genero:["Princesas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Em%20Quebra%20Nozes.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20em%20O%20Quebra%20Nozes.png",
    video:"https://screenapp.io/app/api/public/files/Y78OIWlD_MGI8MvtGxeaKfgx",
    sinopse:"Clara embarca em uma aventura mágica ao lado do Quebra-Nozes para derrotar o Rei dos Ratos.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:3,
    nome:"Barbie como Rapunzel",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2002,
    nota:8.0,
    duracao:"1h24",
    genero:["Princesas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20como%20Rapunzel.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20como%20Rapunzel%205r45.png",
    video:"https://screenapp.io/app/api/public/files/6687QD3Gdl6gwMBflkJLiyMG",
    sinopse:"Rapunzel usa sua coragem e criatividade para mudar seu destino.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:4,
    nome:"Barbie e o Lago dos Cisnes",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2003,
    nota:8.0,
    duracao:"1h23",
    genero:["Princesas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Lago%20dos%20Cisnes.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20em%20Lago%20dos%20Cisnes.png",
    video:"https://screenapp.io/app/api/public/files/tvFw_jxBKR2kd-896wTn_Ozh",
    sinopse:"Odette enfrenta um poderoso feiticeiro para salvar a Floresta Encantada.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:5,
    nome:"Barbie: A Princesa e a Plebeia",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2004,
    nota:8.0,
    duracao:"1h25",
    genero:["Princesas","Musical"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20em%20a%20Princesa%20e%20a%20Plebeia.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20A%20Princesa%20e%20a%20Plebeia.png",
    video:"https://screenapp.io/app/api/public/files/eJuN2ccTZZq4ev3wcvDBjnTl",
    sinopse:"Uma princesa e uma garota comum descobrem que são idênticas e trocam de lugar.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:6,
    nome:"Barbie Fairytopia",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2005,
    nota:8.0,
    duracao:"1h10",
    genero:["Fadas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/barbie%20fairytopia.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Fairytopia.png",
    video:"",
    sinopse:"Elina parte em uma jornada para salvar Fairytopia.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:7,
    nome:"Barbie e a Magia de Pegasus",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2005,
    nota:8.0,
    duracao:"1h25",
    genero:["Princesas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20em%20a%20Magia%20de%20Aladus.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20e%20a%20Magia%20de%20Pegasus.png",
    video:"",
    sinopse:"Annika luta contra um terrível feiticeiro com a ajuda de um cavalo alado.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:8,
    nome:"Barbie Fairytopia Mermaidia",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2006,
    nota:8.0,
    duracao:"1h15",
    genero:["Sereias","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Fairytopia%20Mermaidia.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Fairytopia%20Mermaidia.png",
    video:"",
    sinopse:"Elina viaja para Mermaidia para salvar um príncipe.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:9,
    nome:"O Diário da Barbie",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2006,
    nota:8.0,
    duracao:"1h10",
    genero:["Infantil","Drama"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/O%20Diario%20da%20Barbie%205234.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20O%20Diario%20da%20Barbie.png",
    video:"https://screenapp.io/app/api/public/files/jrvLwfzZUQ9hOKUvk9Kh5tjo",
    sinopse:"Barbie vive os desafios da escola enquanto escreve em seu diário.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:10,
    nome:"Barbie em as 12 Princesas Bailarinas",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2006,
    nota:8.0,
    duracao:"1h22",
    genero:["Princesas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20As%2012%20Princesas%20Bailarinas.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20em%20As%2012%20Princesas%20Bailarinas.png",
    video:"https://screenapp.io/app/api/public/files/99C9iCYestvaej1_wIrwoiY3",
    sinopse:"Doze irmãs descobrem um reino mágico escondido.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:11,
    nome:"Barbie Fairytopia: A Magia do Arco-Íris",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2007,
    nota:8.0,
    duracao:"1h15",
    genero:["Fadas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Fairytopia%20A%20Magia%20do%20Arco%20iris.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Fairytopia%20A%20Magia%20do%20Arco%20iris.png",
    video:"",
    sinopse:"Elina precisa unir as fadas para salvar o primeiro arco-íris da primavera.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:12,
    nome:"Barbie: A Princesa da Ilha",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2007,
    nota:8.0,
    duracao:"1h26",
    genero:["Princesas","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20em%20A%20Princesa%20da%20Ilha.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20A%20Princesa%20da%20Ilha.png",
    video:"https://screenapp.io/app/api/public/files/NNZJth4wRLTxuLBSFuM_SZgO",
    sinopse:"Ro vive em uma ilha paradisíaca até descobrir seu verdadeiro destino como princesa.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:13,
    nome:"Barbie Butterfly A Nova Aventura Em Fairytopia",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2008,
    nota:8.0,
    duracao:"1h15",
    genero:["Fadas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Butterfly%20A%20Nova%20Aventura%20Em%20Fairytopia.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Mariposa%20and%20her%20Butterfly%20Fairy%20Friends.png",
    video:"",
    sinopse:"Mariposa embarca em uma missão para salvar a Rainha das Fadas Borboletas.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:14,
    nome:"Barbie e o Castelo de Diamante",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2008,
    nota:8.0,
    duracao:"1h18",
    genero:["Musical","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/barbie%20castelo%20de%20diamante.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20e%20o%20Castelo%20de%20Diamante.png",
    video:"https://screenapp.io/app/api/public/files/3YRNKvoxFDB2jD7EKpluFxQK",
    sinopse:"Duas amigas enfrentam uma feiticeira para proteger um castelo mágico.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:15,
    nome:"Barbie Em A Canção De Natal",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2008,
    nota:8.0,
    duracao:"1h16",
    genero:["Natal","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Em%20A%20Cancao%20De%20Natal.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Em%20A%20Cancao%20De%20Natal.png",
    video:"https://screenapp.io/app/api/public/files/08VDDkJ3eE0RMUVktTnsXJM-",
    sinopse:"Barbie interpreta uma adaptação encantadora do clássico Conto de Natal.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:16,
    nome:"Barbie Em A Pequena Polegar",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2009,
    nota:8.0,
    duracao:"1h15",
    genero:["Fadas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/4a7d8114438a0ca78cdcc526d790a8ef695669413e4419dc238462c81d3097fb.jpg",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Em%20A%20Pequena%20Polegar.png",
    video:"https://screenapp.io/app/api/public/files/KKhcL2l4NLniZx--nJwnRC1z",
    sinopse:"Polegarzinha descobre que até os menores podem fazer grandes diferenças.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:17,
    nome:"Barbie e as Três Mosqueteiras",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2009,
    nota:8.0,
    duracao:"1h21",
    genero:["Aventura","Princesas"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20as%20Tres%20Mosqueteiras.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20e%20as%20Tres%20Mosqueteiras.png",
    video:"https://screenapp.io/app/api/public/files/QaxAeMg866hSjHTOjV83w3mf",
    sinopse:"Corinne sonha em se tornar mosqueteira e proteger o príncipe.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:18,
    nome:"Barbie em Vida de Sereia",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2010,
    nota:8.0,
    duracao:"1h15",
    genero:["Sereias","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20em%20Vida%20de%20Sereia.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/Barbie%20em%20Vida%20de%20Sereia.png",
    video:"https://screenapp.io/app/api/public/files/Po-dxsUe_6HOpl4omAe826wU",
    trailer: "",
    sinopse:"Merliah descobre que é metade sereia e precisa salvar o reino submarino.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:19,
    nome:"Barbie: Moda e Magia",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2010,
    nota:8.0,
    duracao:"1h19",
    genero:["Fantasia","Moda"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Moda%20e%20Magia.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Moda%20e%20Magia.png",
    video:"https://screenapp.io/app/api/public/files/vGNsb3JYNBepXgnzKKNRmHKu",
    sinopse:"Barbie vai para Paris e ajuda a salvar uma famosa casa de moda.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:20,
    nome:"Barbie: O Segredo das Fadas",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2011,
    nota:8.0,
    duracao:"1h12",
    genero:["Fadas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20E%20o%20Segredo%20Das%20Fadas.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20O%20Segredo%20das%20Fadas.png",
    video:"https://screenapp.io/app/api/public/files/QFIowNIxPqUbfmiIZrFpWIkn",
    sinopse:"Barbie descobre um mundo secreto de fadas enquanto tenta salvar Ken.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:21,
    nome:"Barbie: Escola de Princesas",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2011,
    nota:8.0,
    duracao:"1h20",
    genero:["Princesas","Infantil"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Escola%20de%20Princesas.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Escola%20de%20Princesas.png",
    video:"https://screenapp.io/app/api/public/files/lI3trM26cll2nGWiTXrcwPoj",
    trailer: "",
    sinopse:"Blair é convidada para estudar em uma escola onde aprende a ser princesa.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:22,
    nome:"Barbie: Um Natal Perfeito",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2011,
    nota:8.0,
    duracao:"1h14",
    genero:["Natal","Infantil"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Um%20Natal%20Perfeito.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Um%20Natal%20Perfeito.png",
    video:"https://screenapp.io/app/api/public/files/WjknSVP-HfNT5jLmr-G19NK5",
    sinopse:"Barbie e suas irmãs vivem uma aventura natalina cheia de música e amizade.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:23,
    nome:"Barbie em Vida de Sereia 2",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2012,
    nota:8.0,
    duracao:"1h14",
    genero:["Sereias","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Em%20Vida%20de%20Sereia%202.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20em%20Vida%20de%20Sereia%202.png",
    video:"https://screenapp.io/app/api/public/files/lvCbA4XW3G8WR23y_dqoizaB",
    sinopse:"Merliah retorna ao reino submarino para enfrentar uma nova ameaça.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:24,
    nome:"Barbie: A Princesa e a Pop Star",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2012,
    nota:8.0,
    duracao:"1h26",
    genero:["Musical","Infantil"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20em%20a%20Princesa%20e%20a%20Pop%20Star.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20A%20Princesa%20e%20a%20Pop%20Star.png",
    video:"https://screenapp.io/app/api/public/files/lp862FR_pp4K-mJxEyGFp4x-",
    sinopse:"Uma princesa e uma estrela da música trocam de lugar para descobrir quem realmente são.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:25,
    nome:"Barbie e as Sapatilhas Mágicas",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2013,
    nota:8.0,
    duracao:"1h15",
    genero:["Princesas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20as%20Sapatilhas%20Magicas.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20e%20As%20Sapatilhas%20Magicas.png",
    video:"https://screenapp.io/app/api/public/files/XfrE2Ry7Yqu0R-3d6ybLkQgr",
    trailer: "https://youtu.be/O10GBqtXp4Y?si=OJBUdymxKEg4Gev3",
    sinopse:"Kristyn encontra um par de sapatilhas mágicas que a levam para mundos encantados.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:26,
    nome:"Barbie Mariposa e a Princesa das Fadas",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2013,
    nota:8.0,
    duracao:"1h15",
    genero:["Fadas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Butterfly%20A%20Nova%20Aventura%20Em%20Fairytopia.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Mariposa%20and%20her%20Butterfly%20Fairy%20Friends.png",
    video:"",
    sinopse:"Mariposa faz amizade com uma princesa fada para salvar dois reinos.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:27,
    nome:"Barbie e Suas Irmãs em Uma Aventura de Cavalos",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2013,
    nota:8.0,
    duracao:"1h12",
    genero:["Aventura","Infantil"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20Suas%20Irmas%20em%20uma%20Aventura%20de%20Cavalos.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20e%20Suas%20Irmas%20em%20Uma%20Aventura%20de%20Cavalos.png",
    video:"https://screenapp.io/app/api/public/files/wu9NIWrPvgHvCa8apk0yuIbp",
    sinopse:"Barbie e suas irmãs vivem aventuras inesquecíveis em uma academia de cavalos.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:28,
    nome:"Barbie: A Princesa das Pérolas",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2014,
    nota:8.0,
    duracao:"1h13",
    genero:["Sereias","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20%20A%20sereia%20das%20Perolas.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20A%20Princesa%20das%20Perolas.png",
    video:"https://screenapp.io/app/api/public/files/nWSaNC7LhoXrw7PirPniZGw-",
    sinopse:"Lumina descobre que possui poderes mágicos ligados às pérolas.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:29,
    nome:"Barbie e a Porta Secreta",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2014,
    nota:8.0,
    duracao:"1h21",
    genero:["Princesas","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20o%20Portal%20Secreto.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20e%20o%20Portal%20Secreto.png",
    video:"https://screenapp.io/app/api/public/files/vlNE0GuW2LNqWt1c1ULC8QrR",
    sinopse:"Uma princesa encontra uma porta que leva a um reino mágico cheio de criaturas encantadas.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:30,
    nome:"Barbie Super Princesa",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2015,
    nota:8.0,
    duracao:"1h14",
    genero:["Heroínas","Ação"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20%20Super%20Princesa.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Super%20Princesa.png",
    video:"",
    sinopse:"Depois de ganhar superpoderes, Kara precisa proteger seu reino.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:31,
    nome:"Barbie: Rock'n Royals",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2015,
    nota:8.0,
    duracao:"1h24",
    genero:["Musical","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Rainhas%20do%20Rock.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Rockn%20Royals.png",
    video:"",
    sinopse:"Uma princesa e uma estrela do rock trocam de acampamento e descobrem novos talentos.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:32,
    nome:"Barbie e Suas Irmãs em Uma Aventura de Cachorrinhos",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2015,
    nota:8.0,
    duracao:"1h16",
    genero:["Aventura","Infantil"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20Suas%20Irmas%20em%20Uma%20Aventura%20de%20Cachorrinhos.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20e%20Suas%20Irmas%20em%20Uma%20Aventura%20de%20Cachorrinhos.png",
    video:"",
    sinopse:"Barbie e suas irmãs encontram um mapa do tesouro escondido e vivem uma grande aventura ao lado dos filhotes.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:33,
    nome:"Barbie: E as Agentes Secretas",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2016,
    nota:8.0,
    duracao:"1h15",
    genero:["Espiãs","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20as%20Agentes%20Secretas.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20E%20as%20Agentes%20Secretas.png",
    video:"",
    sinopse:"Barbie e suas amigas se tornam agentes secretas para impedir um misterioso ladrão.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:34,
    nome:"Barbie: Aventura nas Estrelas",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2016,
    nota:8.0,
    duracao:"1h19",
    genero:["Ficção","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Aventura%20Nas%20Estrelas.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Aventura%20nas%20Estrelas.png",
    video:"",
    sinopse:"Barbie viaja pelo espaço para salvar as estrelas da galáxia.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:35,
    nome:"Barbie: Heroína dos Videogames",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2017,
    nota:8.0,
    duracao:"1h12",
    genero:["Videogame","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20em%20Um%20Mundo%20de%20Video%20Game.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Video%20Game%20Hero.png",
    video:"",
    sinopse:"Barbie entra em um videogame e precisa vencer desafios para salvar o mundo digital.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:36,
    nome:"Barbie: Golfinhos Mágicos",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2017,
    nota:8.0,
    duracao:"1h03",
    genero:["Sereias","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20os%20Golfinhos%20Magicos.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Golfinhos%20Magicos.png",
    video:"",
    sinopse:"Durante férias em uma ilha, Barbie conhece golfinhos mágicos e vive uma nova aventura.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:37,
    nome:"Barbie: Aventura de Princesa",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2020,
    nota:8.0,
    duracao:"1h12",
    genero:["Princesas","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Princess%20Adventure.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Aventura%20de%20Princesa.png",
    video:"",
    sinopse:"Barbie conhece uma princesa muito parecida com ela e embarca em uma aventura real.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:38,
    nome:"Barbie: Grande Cidade, Grandes Sonhos",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2021,
    nota:8.0,
    duracao:"1h02",
    genero:["Musical","Infantil"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Grandes%20Sonhos%20na%20Cidade.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Grande%20Cidade%20Grandes%20Sonhos.png",
    video:"",
    sinopse:"As duas Barbies vivem uma emocionante jornada musical em Nova York.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:39,
    nome:"Barbie: O Poder das Sereias",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2022,
    nota:8.0,
    duracao:"1h05",
    genero:["Sereias","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Poder%20da%20Sereia.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20O%20Poder%20das%20Sereias.png",
    video:"",
    sinopse:"Malibu e Brooklyn embarcam em uma aventura submarina para descobrir seus poderes.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:40,
    nome:"Barbie: Skipper e a Grande Aventura de Babá",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2023,
    nota:8.0,
    duracao:"1h00",
    genero:["Aventura","Infantil"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Skipper%20e%20a%20Grande%20Aventura%20de%20Babas.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Skipper%20e%20a%20Grande%20Aventura%20de%20Baba.png",
    video:"",
    sinopse:"Skipper assume um novo desafio enquanto cuida de várias crianças em uma aventura divertida.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:41,
    nome:"Barbie: Uma Viagem Épica",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2022,
    nota:8.0,
    duracao:"36 min",
    genero:["Interativo","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Uma%20Viagem%20epica%20de%20Carro.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Uma%20Viagem%20epica.png",
    video:"",
    sinopse:"Um filme interativo em que você escolhe os caminhos da aventura da Barbie.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:42,
    nome:"Barbie",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2023,
    nota:6.9,
    duracao:"1h 54min",
    genero:["Comédia","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie.png",
    video:"",
    trailer:"https://youtube.com/...",
    sinopse:"Depois de uma crise existencial, Barbie parte para o mundo real.",
    elenco:[ "Margot Robbie", "Ryan Gosling" ],
    diretor:"Greta Gerwig",
    novo:true,
    recomendado:true
},

{
    id:43,
    nome:"Barbie & Chelsea: O Aniversário Perdido",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2021,
    nota:8.0,
    duracao:"1h00",
    genero:["Aventura","Infantil"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20Chelsea%20%20O%20Aniversario%20Perdido.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20e%20Chelsea%20O%20Aniversario%20Perdido.png",
    video:"",
    sinopse:"Chelsea acredita que perdeu seu aniversário durante uma viagem de navio e parte em uma divertida aventura para tentar recuperá-lo.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:44,
    nome:"Barbie e Suas Irmãs em Busca dos Cachorrinhos",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2016,
    nota:8.0,
    duracao:"1h16",
    genero:["Aventura","Infantil"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20Suas%20Irmas%20em%20Busca%20dos%20Cachorrinhos.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20e%20Suas%20Irmas%20em%20Busca%20dos%20Cachorrinhos.png",
    video:"",
    sinopse:"Durante um festival tropical, Barbie e suas irmãs precisam encontrar seus filhotes desaparecidos antes do grande desfile.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:45,
    nome:"Barbie: Vida na Casa dos Sonhos",
    tipo:"Série",
    categoria:"Séries",
    colecao:"Barbie",
    ano:2012,
    nota:8.0,
    duracao:"7 Temporadas",
    genero:["Infantil","Comédia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20A%20Vida%20na%20Casa%20dos%20Sonhos.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Vida%20na%20Casa%20dos%20Sonhos.png",
    video:"",
    sinopse:"Acompanhe Barbie, Ken, suas irmãs e amigos vivendo aventuras engraçadas na famosa Casa dos Sonhos em Malibu.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:46,
    nome:"Barbie Dreamhouse Adventures",
    tipo:"Série",
    categoria:"Séries",
    colecao:"Barbie",
    ano:2018,
    nota:8.0,
    duracao:"5 Temporadas",
    genero:["Infantil","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Aventuras%20na%20Casa%20dos%20Sonhos%20da%20Barbie.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Dreamhouse%20Adventures.png",
    video:"",
    sinopse:"Barbie, suas irmãs e seus amigos vivem novas aventuras, desafios e momentos divertidos na Dreamhouse.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:47,
    nome:"Barbie: São Necessárias Duas",
    tipo:"Série",
    categoria:"Séries",
    colecao:"Barbie",
    ano:2022,
    nota:8.0,
    duracao:"2 Temporadas",
    genero:["Infantil","Musical"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20e%20preciso%20dois.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Sao%20Necessarias%20Duas.png",
    video:"",
    sinopse:"Malibu e Brooklyn seguem seus sonhos na música enquanto vivem novas aventuras e fortalecem sua amizade.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:48,
    nome:"Barbie: Um Toque de Magia",
    tipo:"Série",
    categoria:"Séries",
    colecao:"Barbie",
    ano:2023,
    nota:8.0,
    duracao:"2 Temporadas",
    genero:["Infantil","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Barbie%20Um%20Toque%20de%20Magica.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Um%20Toque%20de%20Magia.png",
    video:"",
    sinopse:"Duas Barbies encontram uma jovem com poderes mágicos e embarcam em aventuras repletas de fantasia.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:50,
    nome:"Barbie Mistérios: A Grande Perseguição a Cavalo",
    tipo:"Série",
    categoria:"Séries",
    colecao:"Barbie",
    ano:2024,
    nota:8.0,
    duracao:"Série",
    genero:["Mistério","Aventura"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Misterios%20da%20Barbie.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20Misterios%20A%20Grande%20Perseguicao%20a%20Cavalo.png",
    video:"",
    sinopse:"Malibu e Brooklyn investigam um misterioso desaparecimento durante uma competição de cavalos.",
    dublado:true,
    legendado:false,
    novo:false
},

{
    id:51,
    nome:"Barbie e Teresa: Receita para a Amizade",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Barbie",
    ano:2025,
    nota:8.8,
    duracao:"1h 02min",
    genero:["Infantil"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Assista%20Barbie%20e%20Teresa%20Receita%20para%20a%20Amizade.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Barbie%20e%20Teresa%20Receita%20para%20a%20Amizade.png",
    dublado:true,
    legendado:true,
    novo:true
},
/*=========================================
            BARBIE
=========================================*/





/*=========================================
            MONSTER HIGH
=========================================*/
{
    id:52,
    nome:"Monster High: O Novo Fantasma da Escola",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"MonsterHigh",
    ano:2010,
    nota:8.0,
    duracao:"23min",
    genero:["Infantil","Fantasia"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20O%20Novo%20Fantasma%20da%20Escola.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20O%20Novo%20Fantasma%20da%20Escola.png",
    video:"",
    novo:false
},

{
    id:53,
    nome:"Monster High: Choque de Cultura: Presas x Pelos",
    ano:2011,
    nota:8.1,
    duracao:"46min",
    genero:["Infantil","Fantasia"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Choque%20de%20Cultura%20Presas%20x%20Pelos.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Choque%20de%20Cultura%20Presas%20x%20Pelos.png",
    video:""
},

{
    id:54,
    nome:"Monster High: Por que os Monstros se Apaixonam?",
    ano:2012,
    nota:8.2,
    duracao:"44min",
    genero:["Romance","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Por%20que%20os%20Monstros%20se%20Apaixonam.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Por%20que%20os%20Monstros%20se%20Apaixonam.png",
    video:""
},

{
    id:55,
    nome:"Monster High: Fuga da Ilha do Esqueleto",
    ano:2012,
    nota:8.0,
    duracao:"45min",
    genero:["Aventura","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Fuga%20da%20Ilha%20do%20Esqueleto.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Fuga%20da%20Ilha%20do%20Esqueleto.png",
    video:""
},

{
    id:56,
    nome:"Monster High: Uma Festa de Arrepiar",
    ano:2012,
    nota:8.0,
    duracao:"46min",
    genero:["Fantasia","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Uma%20Festa%20de%20Arrepiar.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Uma%20Festa%20de%20Arrepiar.png",
    video:""
},

{
    id:57,
    nome:"Monster High: Os Pesadelos de Monster High",
    ano:2012,
    nota:8.0,
    duracao:"46min",
    genero:["Esporte","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Os%20Pesadelos%20de%20Monster%20High.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Os%20Pesadelos%20de%20Monster%20High.png",
    video:""
},

{
    id:58,
    nome:"Monster High: Scaris, a Cidade Sem Luz",
    ano:2013,
    nota:8.2,
    duracao:"61min",
    genero:["Aventura","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Scaris%20City%20of%20Frights.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Scaris%20City%20of%20Frights.png",
    video:""
},

{
    id:59,
    nome:"Monster High: 13 Monster Desejos",
    ano:2013,
    nota:8.5,
    duracao:"73min",
    genero:["Fantasia","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%2013%20Monster%20Desejos.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%2013%20Monster%20Desejos.png",
    video:""
},

{
    id:60,
    nome:"Monster High: Monstros, Câmera, Ação!",
    ano:2014,
    nota:8.4,
    duracao:"74min",
    genero:["Aventura","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Monstros%20Camera%20Acao.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Monstros%20Camera%20Acao.jpg",
    video:""
},

{
    id:61,
    nome:"Monster High: Uma Fusão Muito Louca",
    ano:2014,
    nota:8.1,
    duracao:"73min",
    genero:["Fantasia","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Uma%20Fusao%20Muito%20Louca.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Uma%20Fusao%20Muito%20Louca.png",
    video:""
},

{
    id:62,
    nome:"Monster High: Assombrada",
    ano:2015,
    nota:8.5,
    duracao:"75min",
    genero:["Fantasia","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Haunted.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Haunted.png",
    video:""
},

{
    id:63,
    nome:"Monster High: Boo York, Boo York",
    ano:2015,
    nota:8.3,
    duracao:"72min",
    genero:["Musical","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Boo%20York%20Boo%20York.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Boo%20York%20Boo%20York.png",
    video:""
},

{
    id:64,
    nome:"Monster High: A Assustadora Barreira de Coral",
    ano:2016,
    nota:8.0,
    duracao:"70min",
    genero:["Aventura","Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Great%20Scarrier%20Reef.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Great%20Scarrier%20Reef.png",
    video:""
},

{
    id:65,
    nome:"Bem-Vindos a Monster High",
    ano:2016,
    nota:7.8,
    duracao:"73min",
    genero:["Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20Bem%20Vindos%20a%20Monster%20High.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20Bem%20Vindos%20a%20Monster%20High.png",
    video:""
},

{
    id:66,
    nome:"Monster High: Eletrizante",
    ano:2017,
    nota:7.7,
    duracao:"71min",
    genero:["Infantil"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20Eletrizante.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20Eletrizante.png",
    video:""
},

{
    id:67,
    nome:"Monster High: O Filme",
    ano:2022,
    nota:7.9,
    duracao:"1h 32min",
    genero:["Musical","Fantasia"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%20O%20Filme.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%20O%20Filme.png",
    video:""
},

{
    id:68,
    nome:"Monster High 2",
    ano:2023,
    nota:8.0,
    duracao:"1h 33min",
    genero:["Musical","Fantasia"],
    categoria:"Filmes",
    colecao:"MonsterHigh",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Monster%20High%202.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Monster%20High%202.png",
    video:""
},

/*=========================================
            MONSTER HIGH
=========================================*/





/*=========================================
            FILMES
=========================================*/
{
    id: 69,
    nome: "Obsessão",
    ano: 2025,
    nota: 7.8,
    duracao: "1h 40min",
    genero: ["Suspense","Drama"],
    categoria: "Filmes",
    colecao: "Obsessão",
    tipo: "Filme",
    poster: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/Videos/filme%20obsessao.png",
    banner: "https://onacaokuwgiflhliitlt.supabase.co/storage/v1/object/public/filme/banner%20Obsessao.png",
    video:"",
    pagina: "pages/obsessao.html",
    dublado: true,
    legendado: true,
    novo: true
},

{
    id:70,
    nome:"Um Tira no Jardim da Infância",
    ano:1990,
    nota:6.3,
    duracao:"1h 51min",
    genero:["Ação","Comédia","Crime"],
    categoria:"Filmes",
    colecao:"Arnold Schwarzenegger",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Um%20Tira%20no%20Jardim%20da%20Infancia.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Um%20Tira%20no%20Jardim%20da%20Infancia.png",
    sinopse:"O policial John Kimble precisa se disfarçar de professor de jardim de infância para encontrar a ex-esposa de um perigoso traficante, que pode testemunhar contra ele. Enquanto tenta proteger as crianças e manter seu disfarce, Kimble acaba enfrentando uma situação bem diferente das que está acostumado.",
    video:"https://screenapp.io/app/api/public/files/Zrk7HbjwVQ2Qgs5mfZB8rOTw",
    dublado:true,
    legendado:true,
    novo:false
},

{
    id:71,
    nome:"Burlesque",
    ano:2010,
    nota:6.4,
    duracao:"1h 59min",
    genero:["Filme musical","Comédia","Romance","Drama","Melodrama","Drama Musical"],
    categoria:"Filmes",
    colecao:"Christina Aguilera",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Burlesque.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Burlesque.png",
    sinopse:"Ali é uma jovem do interior com uma grande voz que vai para Los Angeles em busca de seus sonhos. Lá, ela consegue um emprego como garçonete no Burlesque Lounge, um antigo clube comandado por Tess. Encantada pelos figurinos, músicas e coreografias, Ali luta para conseguir uma oportunidade no palco e acaba mostrando que pode ser a grande estrela que o clube precisava.",
    video:"https://screenapp.io/app/api/public/files/FRlzy0VUPrDA1jNoVv1iEfrx",
    dublado:true,
    legendado:true,
    novo:false
},

{
    id:72,
    nome:"V de Vingança",
    ano:2005,
    nota:8.1,
    duracao:"2h 12min",
    genero:["Ficção científica","Ação","Drama","Thriller político","Mistério","Suspense"],
    categoria:"Filmes",
    colecao:"V de Vingança",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/V%20de%20Vinganca.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20V%20de%20Vinganca.png",
    sinopse:"Em uma futura sociedade britânica dominada por um governo autoritário, um misterioso homem conhecido apenas como V inicia um plano para derrubar o regime. Ao conhecer Evey, uma jovem que acaba envolvida em sua missão, V passa a enfrentar forças poderosas enquanto luta por liberdade e justiça.",
    video:"https://screenapp.io/app/api/public/files/SFnOVK65RLzfDX2tdvz5tyiz",
    dublado:true,
    legendado:true,
    novo:false
},

{
    id:73,
    nome:"Um Marido Fiel",
    ano:2022,
    nota:6.5,
    duracao:"1h 44m",
    genero:["Drama", "Noir", "Suspense", "Suspense psicológico", "Crime", "Ficção policial", "Romance psicológico"],
    categoria:"Filmes",
    colecao:"Um Marido Fiel",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Um%20Marido%20Fiel.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Um%20Marido%20Fiel.png",
    sinopse:"A linha tênue entre amor e ódio é colocada à prova quando uma mulher descobre a traição do marido e os dois tomam medidas extremas para conseguir o que querem.",
    video:"",
    dublado:true,
    legendado:true,
    novo:false
},

{
    id:74,
    nome:"Na Trilha da Fama",
    ano:2004,
    nota:5.8,
    duracao:"1h 47min",
    genero:["Drama","Família","Música","Romance"],
    categoria:"Filmes",
    colecao:"Hilary Duff",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Na%20Trilha%20da%20Fama.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Na%20Trilha%20da%20Fama.png",
    sinopse:"Terri Fletcher é uma jovem de uma pequena cidade que sonha em se tornar uma grande cantora. Após uma tragédia pessoal, ela desafia os desejos de seu pai e parte secretamente para Los Angeles, onde passa o verão em uma escola de artes. Lá, Terri conhece novos amigos, enfrenta desafios e descobre mais sobre seu talento, seus sonhos e sobre si mesma.",
    video:"https://screenapp.io/app/api/public/files/g7nLDhF86Ve2sOkO9NwQcEDi",
    dublado:true,
    legendado:true,
    novo:false
},

{
    id:75,
    nome:"Os Intocáveis",
    ano:1987,
    nota:7.8,
    duracao:"1h 59min",
    genero:["Crime","Drama","Policial","Suspense"],
    categoria:"Filmes",
    colecao:"Os Intocáveis",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Os%20Intocaveis.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Os%20Intocaveis.png",
    sinopse:"Durante a Lei Seca em Chicago, o agente federal Eliot Ness tenta acabar com o império criminoso de Al Capone. Diante da corrupção que domina a polícia, Ness reúne uma pequena equipe de homens incorruptíveis, contando com a ajuda do experiente policial Jim Malone. Juntos, eles enfrentam a organização de Capone em uma perigosa batalha contra o crime e a corrupção.",
    video:"https://screenapp.io/app/api/public/files/SdhG_tWYGpx_e4QGjXXItY1P",
    dublado:true,
    legendado:true,
    novo:false
},

{
    id:76,
    nome:"Michael",
    ano:2026,
    nota:7.4,
    duracao:"2h 07min",
    genero:["Biografia","Drama","Musical"],
    categoria:"Filmes",
    colecao:"Michael Jackson",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Michael.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Michael.png",
    sinopse:"Michael é uma cinebiografia musical sobre Michael Jackson, acompanhando sua trajetória desde a descoberta de seu talento extraordinário como líder do Jackson Five até sua ascensão como um dos maiores artistas do mundo. O filme também mostra sua vida fora dos palcos, suas ambições criativas e algumas das performances mais marcantes do início de sua carreira solo.",
    video:"https://screenapp.io/app/api/public/files/tqAfoTwgDZyTxzu3QnG_LHMn",
    trailer: "https://youtu.be/14YXeHKOBUY?si=zZAsYo44pVaGHk6f",
    dublado:true,
    legendado:true,
    novo:true
},

{
    id:77,
    nome:"Interestelar",
    ano:2014,
    nota:8.7,
    duracao:"2h 49min",
    genero:["Drama","Ficção Científica","Aventura"],
    categoria:"Filmes",
    colecao:"Christopher Nolan",
    tipo:"Filme",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Interestelar.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Interestelar%20364536.png",
    sinopse:"Em um futuro em que a Terra está se tornando cada vez mais inabitável, o ex-piloto da NASA Cooper é escolhido para liderar uma missão espacial em busca de um novo lar para a humanidade. Ao lado de outros astronautas, ele atravessa um buraco de minhoca e explora mundos distantes, enquanto enfrenta os efeitos do tempo, da distância e das escolhas que fez ao deixar sua família para trás.",
    video:"https://screenapp.io/app/api/public/files/RorFrXh1SUAWFMxwENaaMAb-",
    trailer: "https://youtu.be/i6avfCqKcQo?si=A2GYm6vtbIu--eZn",
    dublado:true,
    legendado:true,
    novo:false
},

{
    id:78,
    nome: "Mestres do Universo",
    tipo: "Filme",
    categoria: "Filmes",
    colecao: "Mestres do Universo",
    subcategoria: "Aventura",
    ano: 2026,
    duracao: "2h 20min",
    genero: ["Ação", "Aventura", "Fantasia", "Ficção Científica"],
    idioma: "🇺🇸 Inglês",
    qualidade: "1080P",
    classificacao: "14 anos",
    poster: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Mestres%20do%20Universo.png",
    banner: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Mestres%20do%20Universo.png",
    video: "https://screenapp.io/app/api/public/files/csBJ29yosJUkEiINcdiKzi8Z",
    trailer: "https://youtu.be/YLWDrS8qCiM?si=F82H04bn4Tq-rKrT",
    dublado: true,
    legendado: true,
    novo: true,
    sinopse: "Após perder a Espada do Poder e ser separado de Eternia ainda criança, Adam a recupera quase 20 anos depois e retorna ao seu planeta natal. Agora, com Eternia dominada pelo maligno Esqueleto, ele precisa descobrir seu verdadeiro passado, aceitar seu destino como He-Man e lutar ao lado de Teela e Duncan para salvar seu mundo."
},

{
    id:79,
    nome: "Supergirl",
    tipo: "Filme",
    categoria: "Filmes",
    colecao: "DC",
    subcategoria: "Aventura",
    ano: 2026,
    duracao: "1h 50m",
    genero: ["Ficção", "Aventura", "Divertido", "Aventura"],
    idioma: "🇺🇸 Inglês",
    qualidade: "1080P",
    classificacao: "14 anos",
    poster: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Supergirl.png",
    banner: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Supergirl.png",
    video: "https://screenapp.io/app/api/public/files/ZPox2F5EF0F_ZrfidCVJ2AaR",
    trailer: "https://youtu.be/XvaUMy2LcOQ?si=-J72N1QEBpGXDq6o",
    dublado: true,
    legendado: true,
    novo: true,
    sinopse: "Quando um adversário inesperado e implacável ataca, Kara Zor-El, a Supergirl, forja uma aliança improvável, a contragosto, em uma épica jornada interestelar em busca de justiça e vingança."
},

{
    id: 80,
    nome: "Piratas do Caribe: O Baú da Morte",
    tipo: "Filme",
    categoria: "Filmes",
    colecao: "Piratas do Caribe",
    subcategoria: "Aventura",
    ano: 2006,
    duracao: "2h 31min",
    genero: [ "Ação", "Aventura", "Fantasia" ],
    idioma: "🇺🇸 Inglês",
    qualidade: "1080P",
    classificacao: "14 anos",
    poster: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Piratas%20do%20Caribe%20O%20Ba%20da%20Morte.png",
    banner: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Piratas%20do%20Caribe%20O%20Bau%20da%20Morte.png",
    nota: 7.4,
    trailer: "",
    video: "https://screenapp.io/app/api/public/files/VslHzrIQ0dDVBqjlDdkoAFyV",
    sinopse: "O Capitão Jack Sparrow descobre que tem uma dívida de sangue com Davy Jones, o lendário capitão do Holandês Voador. Enquanto tenta escapar de seu destino, Jack se envolve em uma nova aventura ao lado de Will Turner e Elizabeth Swann."
},

{
    id: 81,
    nome: "Avatar",
    tipo: "Filme",
    categoria: "Filmes",
    colecao: "Avatar",
    subcategoria: "Ficção Científica",
    ano: 2009,
    duracao: "2h 41min",
    genero: [ "Ação", "Aventura", "Fantasia", "Ficção Científica" ],
    idioma: "🇺🇸 Inglês",
    qualidade: "1080P",
    classificacao: "13 anos",
    poster: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Avatar.png",
    banner: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Avatar.png",
    nota: 7.8,
    trailer: "",
    video: "https://screenapp.io/app/api/public/files/qlCoVNi3KC_mkbuoAieORpeC",
    sinopse: "No ano de 2154, o ex-fuzileiro naval Jake Sully é enviado para Pandora, uma lua distante onde uma corporação explora um mineral raro. Usando um avatar, Jake entra em contato com os Na'vi e começa a questionar sua missão enquanto se envolve com a cultura do povo e com Neytiri."
},

{
    id: 82,
    nome: "Avatar: O Caminho da Água",
    tipo: "Filme",
    categoria: "Filmes",
    colecao: "Avatar",
    subcategoria: "Ficção Científica",
    ano: 2022,
    duracao: "3h 12min",
    genero: [ "Ação", "Aventura", "Fantasia", "Ficção Científica" ],
    idioma: "🇺🇸 Inglês",
    qualidade: "1080P",
    classificacao: "12 anos",
    poster: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Avatar%20O%20Caminho%20da%20agua.png",
    banner: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Avatar%20O%20Caminho%20da%20agua.png",
    nota: 7.6,
    trailer: "https://youtu.be/ZgQszxRY3GU?si=jK7PD68xbsy_eQv5",
    video: "https://screenapp.io/app/api/public/files/t5EEOqTvfaqilw_ZhZ7dIquX",
    sinopse: "Mais de uma década após os acontecimentos do primeiro filme, Jake Sully e Neytiri vivem em Pandora com seus filhos. Quando uma antiga ameaça retorna, a família precisa deixar seu lar e buscar refúgio entre um novo povo Na'vi, enquanto enfrenta perigos nos oceanos de Pandora."
},

{
    id: 83,
    nome: "Truque de Mestre",
    tipo: "Filme",
    categoria: "Filmes",
    colecao: "Truque de Mestre",
    subcategoria: "Suspense",
    ano: 2013,
    duracao: "2h 05min",
    genero: ["Suspense", "Crime", "Mistério"],
    idioma: "🇺🇸 Inglês",
    qualidade: "1080P",
    classificacao: "12 anos",
    poster: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/truque%20de%20mestre.png",
    banner: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20truque%20de%20mestre.png",
    nota: 7.2,
    trailer: "https://youtu.be/iRKur9czUOo?si=ZLcQYTSn-PSgwh34",
    video: "https://screenapp.io/app/api/public/files/aUL-bmQOZwm3lv-VVKfkLMbt",
    sinopse: "Um grupo de ilusionistas conhecido como Os Quatro Cavaleiros realiza espetáculos impressionantes enquanto também executa ousados assaltos a bancos. Um agente do FBI e uma detetive da Interpol tentam descobrir como os mágicos conseguem realizar seus crimes e desvendar o verdadeiro segredo por trás dos truques."
},

{
    id: 84,
    nome: "Truque de Mestre: O 2º Ato",
    tipo: "Filme",
    categoria: "Filmes",
    colecao: "Truque de Mestre",
    subcategoria: "Suspense",
    ano: 2016,
    duracao: "2h 09min",
    genero: ["Ação", "Aventura", "Comédia", "Crime", "Mistério", "Suspense"],
    idioma: "🇺🇸 Inglês",
    qualidade: "1080P",
    classificacao: "12 anos",
    poster: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/truque%20de%20mestre%20o%202o%20ato.png",
    banner: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20truque%20de%20mestre%20o%202o%20ato.png",
    nota: 6.4,
    trailer: "https://youtu.be/8Q6jGcM2Kos?si=KqMNFbspPDvXjrMc",
    video: "https://screenapp.io/app/api/public/files/rtlHr6GTp3J8nciIywSUMR5p",
    sinopse: "Um ano após despistar o FBI, os Quatro Cavaleiros retornam para realizar um novo espetáculo. O plano envolve expor as práticas de um poderoso magnata da tecnologia, mas a apresentação é interrompida e o grupo acaba sendo levado para uma missão envolvendo um misterioso gênio da tecnologia."
},

{
    id: 85,
    nome: "Enola Holmes",
    tipo: "Filme",
    categoria: "Filmes",
    colecao: "Enola Holmes",
    subcategoria: "Mistério",
    ano: 2020,
    duracao: "2h 03min",
    genero: ["Mistério", "Aventura", "Ação", "Crime", "Drama"],
    idioma: "🇺🇸 Inglês",
    qualidade: "1080P",
    classificacao: "12 anos",
    poster: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Enola%20Holmes.png",
    banner: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Enola%20Holmes%20645645756.png",
    nota: 6.7,
    trailer: "https://youtu.be/rcV1I-397Wg?si=k4I5MSSv-62DHX6L",
    video: "https://screenapp.io/app/api/public/files/5frYiQlkmTu_-Z6Nrygd1qL6",
    sinopse: "Quando sua mãe desaparece misteriosamente no aniversário de 16 anos, Enola Holmes parte em uma aventura para encontrá-la. Enquanto foge dos planos de seus irmãos Sherlock e Mycroft, ela acaba envolvida na busca por um jovem lorde fugitivo e descobre uma conspiração que pode mudar o futuro do país."
},

{
    id: 86,
    nome: "Enola Holmes 2",
    tipo: "Filme",
    categoria: "Filmes",
    colecao: "Enola Holmes",
    subcategoria: "Mistério",
    ano: 2022,
    duracao: "2h 09min",
    genero: ["Mistério", "Aventura", "Ação", "Crime", "Drama"],
    idioma: "🇺🇸 Inglês",
    qualidade: "1080P",
    classificacao: "14 anos",
    poster: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/enola%20holmes%202.png",
    banner: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20enola%20holmes%202.png",
    nota: 6.8,
    trailer: "https://www.youtube.com/watch?v=3t0F8Dg3Fvw",
    video: "https://screenapp.io/app/api/public/files/0kExCBR2yMEzvQ0GbpOoSxKn",
    sinopse: "Em seu primeiro caso oficial como detetive, Enola Holmes é contratada para encontrar uma menina desaparecida. A investigação logo revela uma conspiração muito maior, levando Enola a percorrer as ruas de Londres e a contar com a ajuda de seus amigos e de seu irmão, Sherlock Holmes."
},

{
    id: 87,
    nome: "Enola Holmes 3",
    tipo: "Filme",
    categoria: "Filmes",
    colecao: "Enola Holmes",
    subcategoria: "Mistério",
    ano: 2026,
    duracao: "1h 45min",
    genero: ["Mistério", "Aventura", "Ação", "Drama"],
    idioma: "🇺🇸 Inglês",
    qualidade: "1080P",
    classificacao: "14 anos",
    poster: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/enola%20holmes%203.png",
    banner: "https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20enola%20holmes%203.png",
    nota: 7.0,
    trailer: "https://www.youtube.com/watch?v=n_pEJjq-9xQ",
    video: "https://screenapp.io/app/api/public/files/ylu7iHxLJWqduqeoI6PmUINE",
    sinopse: "A detetive Enola Holmes viaja para Malta, onde seus planos de se casar com Lorde Tewkesbury são interrompidos quando seu irmão Sherlock desaparece. Enquanto procura por ele, Enola se envolve em um novo e perigoso mistério, repleto de pistas, conspirações e segredos."
},

{
    id: 88,
    nome:"Um Sonho de Liberdade",
    tipo:"Filme",
    categoria:"Filmes",
    ano:1994,
    nota:9.3,
    duracao:"2h22min",
    genero:["Drama"],
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Um%20Sonho%20de%20Liberdade.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Um%20Sonho%20de%20Liberdade.png",
    video:"https://screenapp.io/app/api/public/files/-0PQK77VRhnxtRhtFXz7_OCE",
    sinopse:"Andy Dufresne é condenado à prisão perpétua por um crime que afirma não ter cometido. Na prisão, ele constrói uma amizade marcante com Red e mantém viva a esperança de liberdade.",
    dublado:true,
    legendado:true,
    novo:false
},

{
    id:89,
    nome:"Truque de Mestre: O 3º Ato",
    tipo:"Filme",
    categoria:"Filmes",
    colecao:"Truque de Mestre",
    subcategoria:"Suspense",
    ano:2025,
    duracao:"1h 53min",
    genero:["Ação","Aventura","Crime","Mistério","Suspense"],
    idioma:"🇺🇸 Inglês",
    qualidade:"1080P",
    classificacao:"12 anos",
    poster:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/poster/Truque%20de%20Mestre%20O%203%20Ato.png",
    banner:"https://zwgzxewhpmxyksfripti.supabase.co/storage/v1/object/public/banner/banner%20Truque%20de%20Mestre%20O%203%20Ato.png",
    nota:5.9,
    trailer:"https://www.youtube.com/watch?v=-E3lMRx7HRQ",
    video:"https://screenapp.io/app/api/public/files/74NMx10Cl35rYUlqKSGUk3JP",
    sinopse:"Os Quatro Cavaleiros estão de volta com uma nova geração de ilusionistas para realizar um novo e ousado golpe envolvendo uma das joias mais valiosas do mundo. Entre ilusões, reviravoltas e perigos, os dois grupos precisam se unir para enfrentar criminosos poderosos.",
    dublado:true,
    legendado:true,
    novo:true
},

];