const FILMES = [

{
    id: 1,
    titulo: "Barbie in the Nutcracker",
    tituloPT: "Barbie em O Quebra-Nozes",
    ano: 2001,
    categoria: "Princesas",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h16",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Clara embarca em uma aventura mágica ao lado do Quebra-Nozes para derrotar o Rei dos Ratos."
},

{
    id: 2,
    titulo: "Barbie as Rapunzel",
    tituloPT: "Barbie como Rapunzel",
    ano: 2002,
    categoria: "Princesas",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h24",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Rapunzel usa sua coragem e criatividade para mudar seu destino."
},

{
    id: 3,
    titulo: "Barbie of Swan Lake",
    tituloPT: "Barbie e o Lago dos Cisnes",
    ano: 2003,
    categoria: "Princesas",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h23",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Odette enfrenta um poderoso feiticeiro para salvar a Floresta Encantada."
},

{
    id: 4,
    titulo: "Barbie as the Princess and the Pauper",
    tituloPT: "Barbie: A Princesa e a Plebeia",
    ano: 2004,
    categoria: "Princesas",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h25",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Uma princesa e uma garota comum descobrem que são idênticas e trocam de lugar."
},

{
    id: 5,
    titulo: "Barbie Fairytopia",
    tituloPT: "Barbie Fairytopia",
    ano: 2005,
    categoria: "Fadas",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h10",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Elina parte em uma jornada para salvar Fairytopia."
},

{
    id: 6,
    titulo: "Barbie and the Magic of Pegasus",
    tituloPT: "Barbie e a Magia de Pegasus",
    ano: 2005,
    categoria: "Princesas",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h25",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Annika luta contra um terrível feiticeiro com a ajuda de um cavalo alado."
},

{
    id: 7,
    titulo: "Barbie Mermaidia",
    tituloPT: "Barbie Mermaidia",
    ano: 2006,
    categoria: "Sereias",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h15",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Elina viaja para Mermaidia para salvar um príncipe."
},

{
    id: 8,
    titulo: "The Barbie Diaries",
    tituloPT: "O Diário da Barbie",
    ano: 2006,
    categoria: "Modernos",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h10",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Barbie vive os desafios da escola enquanto escreve em seu diário."
},

{
    id: 9,
    titulo: "Barbie in the 12 Dancing Princesses",
    tituloPT: "Barbie em as 12 Princesas Bailarinas",
    ano: 2006,
    categoria: "Princesas",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h22",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Doze irmãs descobrem um reino mágico escondido."
},

{
    id: 10,
    titulo: "Barbie Fairytopia: Magic of the Rainbow",
    tituloPT: "Barbie Fairytopia: A Magia do Arco-Íris",
    ano: 2007,
    categoria: "Fadas",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h15",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Elina precisa unir as fadas para salvar o primeiro arco-íris da primavera."
},

{
    id: 11,
    titulo: "Barbie as the Island Princess",
    tituloPT: "Barbie: A Princesa da Ilha",
    ano: 2007,
    categoria: "Princesas",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h26",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Ro vive em uma ilha paradisíaca até descobrir seu verdadeiro destino como princesa."
},

{
    id: 12,
    titulo: "Barbie Mariposa",
    tituloPT: "Barbie Mariposa",
    ano: 2008,
    categoria: "Fadas",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h15",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Mariposa embarca em uma missão para salvar a Rainha das Fadas Borboletas."
},

{
    id: 13,
    titulo: "Barbie and the Diamond Castle",
    tituloPT: "Barbie e o Castelo de Diamante",
    ano: 2008,
    categoria: "Musicais",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h18",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Duas amigas enfrentam uma feiticeira para proteger um castelo mágico."
},

{
    id: 14,
    titulo: "Barbie in A Christmas Carol",
    tituloPT: "Barbie em Conto de Natal",
    ano: 2008,
    categoria: "Natal",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h16",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Barbie interpreta uma adaptação encantadora do clássico Conto de Natal."
},

{
    id: 15,
    titulo: "Barbie Presents: Thumbelina",
    tituloPT: "Barbie Apresenta: Polegarzinha",
    ano: 2009,
    categoria: "Fadas",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h15",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Polegarzinha descobre que até os menores podem fazer grandes diferenças."
},

{
    id: 16,
    titulo: "Barbie and the Three Musketeers",
    tituloPT: "Barbie e as Três Mosqueteiras",
    ano: 2009,
    categoria: "Aventura",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h21",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Corinne sonha em se tornar mosqueteira e proteger o príncipe."
},

{
    id: 17,
    titulo: "Barbie in A Mermaid Tale",
    tituloPT: "Barbie em Vida de Sereia",
    ano: 2010,
    categoria: "Sereias",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h15",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Merliah descobre que é metade sereia e precisa salvar o reino submarino."
},

{
    id: 18,
    titulo: "Barbie: A Fashion Fairytale",
    tituloPT: "Barbie: Moda e Magia",
    ano: 2010,
    categoria: "Modernos",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h19",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Barbie vai para Paris e ajuda a salvar uma famosa casa de moda."
},

{
    id: 19,
    titulo: "Barbie: A Fairy Secret",
    tituloPT: "Barbie: O Segredo das Fadas",
    ano: 2011,
    categoria: "Fadas",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h12",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Barbie descobre um mundo secreto de fadas enquanto tenta salvar Ken."
},

{
    id: 20,
    titulo: "Barbie: Princess Charm School",
    tituloPT: "Barbie: Escola de Princesas",
    ano: 2011,
    categoria: "Princesas",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h20",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Blair é convidada para estudar em uma escola onde aprende a ser princesa."
},

{
    id: 21,
    titulo: "Barbie: A Perfect Christmas",
    tituloPT: "Barbie: Um Natal Perfeito",
    ano: 2011,
    categoria: "Natal",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h14",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Barbie e suas irmãs vivem uma aventura natalina cheia de música e amizade."
},

{
    id: 22,
    titulo: "Barbie in A Mermaid Tale 2",
    tituloPT: "Barbie em Vida de Sereia 2",
    ano: 2012,
    categoria: "Sereias",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h14",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Merliah retorna ao reino submarino para enfrentar uma nova ameaça."
},

{
    id: 23,
    titulo: "Barbie: The Princess & the Popstar",
    tituloPT: "Barbie: A Princesa e a Pop Star",
    ano: 2012,
    categoria: "Musicais",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h26",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Uma princesa e uma estrela da música trocam de lugar para descobrir quem realmente são."
},

{
    id: 24,
    titulo: "Barbie in the Pink Shoes",
    tituloPT: "Barbie e as Sapatilhas Mágicas",
    ano: 2013,
    categoria: "Princesas",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h15",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Kristyn encontra um par de sapatilhas mágicas que a levam para mundos encantados."
},

{
    id: 25,
    titulo: "Barbie: Mariposa & the Fairy Princess",
    tituloPT: "Barbie Mariposa e a Princesa das Fadas",
    ano: 2013,
    categoria: "Fadas",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h15",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Mariposa faz amizade com uma princesa fada para salvar dois reinos."
},

{
    id: 26,
    titulo: "Barbie & Her Sisters in A Pony Tale",
    tituloPT: "Barbie e Suas Irmãs em Uma Aventura de Cavalos",
    ano: 2013,
    categoria: "Aventura",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h12",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Barbie e suas irmãs vivem aventuras inesquecíveis em uma academia de cavalos."
},

{
    id: 27,
    titulo: "Barbie: The Pearl Princess",
    tituloPT: "Barbie: A Princesa das Pérolas",
    ano: 2014,
    categoria: "Sereias",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h13",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Lumina descobre que possui poderes mágicos ligados às pérolas."
},

{
    id: 28,
    titulo: "Barbie and the Secret Door",
    tituloPT: "Barbie e a Porta Secreta",
    ano: 2014,
    categoria: "Princesas",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h21",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Uma princesa encontra uma porta que leva a um reino mágico cheio de criaturas encantadas."
},

{
    id: 29,
    titulo: "Barbie in Princess Power",
    tituloPT: "Barbie Super Princesa",
    ano: 2015,
    categoria: "Heroínas",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h14",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Depois de ganhar superpoderes, Kara precisa proteger seu reino."
},

{
    id: 30,
    titulo: "Barbie in Rock 'N Royals",
    tituloPT: "Barbie: Rock'n Royals",
    ano: 2015,
    categoria: "Musicais",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h24",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Uma princesa e uma estrela do rock trocam de acampamento e descobrem novos talentos."
},

{
    id: 31,
    titulo: "Barbie & Her Sisters in the Great Puppy Adventure",
    tituloPT: "Barbie e Suas Irmãs em Uma Aventura de Cachorrinhos",
    ano: 2015,
    categoria: "Aventura",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h16",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Barbie e suas irmãs encontram um mapa do tesouro escondido e vivem uma grande aventura ao lado dos filhotes."
},

{
    id: 32,
    titulo: "Barbie: Spy Squad",
    tituloPT: "Barbie: Equipe de Espiãs",
    ano: 2016,
    categoria: "Espiãs",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h15",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Barbie e suas amigas se tornam agentes secretas para impedir um misterioso ladrão."
},

{
    id: 33,
    titulo: "Barbie: Star Light Adventure",
    tituloPT: "Barbie: Aventura nas Estrelas",
    ano: 2016,
    categoria: "Ficção",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h19",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Barbie viaja pelo espaço para salvar as estrelas da galáxia."
},

{
    id: 34,
    titulo: "Barbie: Video Game Hero",
    tituloPT: "Barbie: Heroína dos Videogames",
    ano: 2017,
    categoria: "Videogame",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h12",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Barbie entra em um videogame e precisa vencer desafios para salvar o mundo digital."
},

{
    id: 35,
    titulo: "Barbie Dolphin Magic",
    tituloPT: "Barbie: Golfinhos Mágicos",
    ano: 2017,
    categoria: "Sereias",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h03",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Durante férias em uma ilha, Barbie conhece golfinhos mágicos e vive uma nova aventura."
},

{
    id: 36,
    titulo: "Barbie Princess Adventure",
    tituloPT: "Barbie: Aventura de Princesa",
    ano: 2020,
    categoria: "Princesas",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h12",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Barbie conhece uma princesa muito parecida com ela e embarca em uma aventura real."
},

{
    id: 37,
    titulo: "Barbie: Big City, Big Dreams",
    tituloPT: "Barbie: Grande Cidade, Grandes Sonhos",
    ano: 2021,
    categoria: "Musicais",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h02",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "As duas Barbies vivem uma emocionante jornada musical em Nova York."
},

{
    id: 38,
    titulo: "Barbie: Mermaid Power",
    tituloPT: "Barbie: O Poder das Sereias",
    ano: 2022,
    categoria: "Sereias",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h05",
    poster: "",
    banner: "",
   video: "",
    favorito: false,
    sinopse: "Malibu e Brooklyn embarcam em uma aventura submarina para descobrir seus poderes."
},

{
    id: 39,
    titulo: "Barbie: Skipper and the Big Babysitting Adventure",
    tituloPT: "Barbie: Skipper e a Grande Aventura de Babá",
    ano: 2023,
    categoria: "Aventura",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h00",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Skipper assume um novo desafio enquanto cuida de várias crianças em uma aventura divertida."
},

{
    id: 40,
    titulo: "Barbie: Epic Road Trip",
    tituloPT: "Barbie: Uma Viagem Épica",
    ano: 2022,
    categoria: "Interativo",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "36 min",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Um filme interativo em que você escolhe os caminhos da aventura da Barbie."
},

{
    id: 41,
    titulo: "Barbie",
    tituloPT: "Barbie",
    ano: 2023,
    categoria: "Live Action",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "12",
    duracao: "1h54",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Barbie parte para o mundo real e descobre que a vida é muito diferente da Barbielândia."
},

{
    id: 42,
    titulo: "Barbie and Teresa: Recipe for Friendship",
    tituloPT: "Barbie e Teresa: Receita para a Amizade",
    ano: 2025,
    categoria: "Animação",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h01",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Barbie e Teresa descobrem que cozinhar juntas fortalece ainda mais a amizade."
},

{
    id: 43,
    titulo: "Barbie Mysteries: The Great Horse Chase",
    tituloPT: "Barbie Mistérios: A Grande Perseguição a Cavalo",
    ano: 2024,
    categoria: "Série",
    tipo: "serie",
    pagina:"barbie-mysteries.html",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "Série",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Malibu e Brooklyn investigam um misterioso desaparecimento durante uma competição de cavalos."
},

{
    id: 45,
    titulo: "Barbie & Chelsea: The Lost Birthday",
    tituloPT: "Barbie e Chelsea: O Aniversário Perdido",
    ano: 2021,
    categoria: "Aventura",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h00",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Chelsea acredita que perdeu seu aniversário durante uma viagem de navio e parte em uma divertida aventura para tentar recuperá-lo."
},

{
    id: 46,
    titulo: "Barbie & Her Sisters in a Puppy Chase",
    tituloPT: "Barbie e Suas Irmãs em Uma Caçada aos Filhotes",
    ano: 2016,
    categoria: "Aventura",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "1h16",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Durante um festival tropical, Barbie e suas irmãs precisam encontrar seus filhotes desaparecidos antes do grande desfile."
},

{
    id: 47,
    titulo: "Barbie and the Rockers: Out of This World",
    tituloPT: "Barbie e os Rockers: Fora Deste Mundo",
    ano: 1987,
    categoria: "Musical",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "25 min",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Barbie e sua banda, os Rockers, embarcam em uma aventura espacial para realizar um show inesquecível e descobrir que a música pode unir pessoas de diferentes mundos."
},

{
    id: 48,
    titulo: "Barbie: Life in the Dreamhouse",
    tituloPT: "Barbie: Vida na Casa dos Sonhos",
    ano: 2012,
    categoria: "Série",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "7 Temporadas",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Acompanhe Barbie, Ken, suas irmãs e amigos vivendo aventuras engraçadas na famosa Casa dos Sonhos em Malibu."
},

{
    id: 49,
    titulo: "Barbie Dreamhouse Adventures",
    tituloPT: "Barbie Dreamhouse Adventures",
    ano: 2018,
    categoria: "Série",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "5 Temporadas",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Barbie, suas irmãs e seus amigos vivem novas aventuras, desafios e momentos divertidos na Dreamhouse."
},

{
    id: 50,
    titulo: "Barbie: It Takes Two",
    tituloPT: "Barbie: São Necessárias Duas",
    ano: 2022,
    categoria: "Série",
    tipo: "serie",
    pagina:"html",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "2 Temporadas",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Malibu e Brooklyn seguem seus sonhos na música enquanto vivem novas aventuras e fortalecem sua amizade."
},

{
    id: 51,
    titulo: "Barbie: A Touch of Magic",
    tituloPT: "Barbie: Um Toque de Magia",
    ano: 2023,
    categoria: "Série",
    tipo: "serie",
    pagina:"html",
    idioma: "🇧🇷 Dublado",
    qualidade: "1080P",
    classificacao: "Livre",
    duracao: "2 Temporadas",
    poster: "",
    banner: "",
    video: "",
    favorito: false,
    sinopse: "Duas Barbies encontram uma jovem com poderes mágicos e embarcam em aventuras repletas de fantasia."
},


];